### ISSUE TITLE
/srv and /shaer/searx

### ISSUE THREAD

**Issue by return42** [dalf/searx-install#3]
https://github.com/dalf/searx-install/blob/e0e9276f2b69f7c3b7bbbc7ce7233b2f93b78f67/shared/test/setup.sh#L4

chmod has to be applied on `/src/searx` not ..

https://github.com/dalf/searx-install/blob/e0e9276f2b69f7c3b7bbbc7ce7233b2f93b78f67/shared/test/setup.sh#L14

**Comment by dalf** [comment]
See 629e86890d78328417bf9b5c779def6aca56c2df
